### PR TITLE
Ds ab test2

### PR DESCRIPTION
**Pull request by dashasandler**
Changed the names for describe and it

### CODE REVIEW

**Comment by BurhanH** [comment]
@dashasandler please sync your PR with latest changes in the repository
Thanks

**Comment by Stan575** [comment]
@dashasandler Please resolve the conflicts

**Comment by dashasandler** [comment]
> @dashasandler please sync your PR with latest changes in the repository Thanks

did it, thanks!

**Comment by BurhanH** [comment]
Don't use 2-advanced-examples.
Don't push empty files.

**Pull request closed without merging**
